---

- name: Delete instance {{ docker_deploy_name }}
  become: true
  ansible.builtin.file:
    path: "{{ docker_deploy_base_dir }}/{{ docker_deploy_name }}"
    state: absent

- name: Delete Docker volumes
  vars:
    docker_volume_state: absent
  ansible.builtin.include_tasks: docker_volume.yml
  loop: "{{ docker_deploy_volumes | default([]) }}"
  loop_control:
    loop_var: docker_volume

- name: Delete Docker networks
  vars:
    docker_network_state: absent
  ansible.builtin.include_tasks: docker_network.yml
  loop: "{{ docker_deploy_networks | default([]) }}"
  loop_control:
    loop_var: docker_network

- name: Delete systemd service docker-compose@{{ docker_deploy_name }}
  become: true
  ansible.builtin.systemd_service:
    name: docker-compose@{{ docker_deploy_name }}.service
    enabled: false
    daemon_reload: true
    state: stopped

...
