---

- name: Make sure directories are existing
  become: true
  ansible.builtin.file:
    path: "{{ docker_deploy_base_dir }}/{{ docker_deploy_name }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('u=rwx,go=rx') }}"
  loop: "{{ docker_deploy_directories }}"
  loop_control:
    label: "{{ item.path }}"

...
