---

- name: Gather list of files
  ansible.builtin.set_fact:
    docker_deploy_files: >-
      {{ docker_deploy_files | default([]) + lookup('community.general.filetree', '{{ item }}', wantlist=true) }}
  loop: "{{ docker_deploy_file_dirs | default([]) }}"

- name: Make sure destination directories for files exists
  become: true
  ansible.builtin.file:
    path: "{{ docker_deploy_base_dir }}/{{ docker_deploy_name }}/{{ item }}"
    state: directory
    mode: u=rwx,go=rx
  loop: "{{ docker_deploy_files | selectattr('state', 'equalto', 'directory') | map(attribute='path') | unique }}"

- name: Deploy files
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ docker_deploy_base_dir }}/{{ docker_deploy_name }}/{{ item.path }}"
    mode: "{{ item.mode | default('u=rw,go=r') }}"
  loop: "{{ docker_deploy_files | selectattr('state', 'equalto', 'file') }}"
  loop_control:
    label: "{{ item.path }}"
  register: docker_deploy_file_status

...
