---

- name: Check deploy base dir name
  ansible.builtin.assert:
    that:
      - docker_deploy_base_dir is defined
      - docker_deploy_base_dir is string
      - docker_deploy_base_dir | length > 0
      - docker_deploy_base_dir != '/'
    fail_msg: "'docker_deploy_base_dir' must be a non-empty string"
    success_msg: "'docker_deploy_base_dir' is valid"
    quiet: true

- name: Check instance name
  ansible.builtin.assert:
    that:
      - docker_deploy_name is defined
      - docker_deploy_name is string
      - docker_deploy_name | length > 0
      - "'/' not in docker_deploy_name"
    fail_msg: "'docker_deploy_name' must be a non-empty string"
    success_msg: "'docker_deploy_name' is valid"
    quiet: true

- name: Check instance state
  ansible.builtin.assert:
    that:
      - docker_deploy_state in ['present', 'absent', 'deactivated']
    fail_msg: "'docker_deploy_state' must be 'present', 'absent', or 'deactivated'"
    success_msg: "'docker_deploy_state' is valid"
    quiet: true

- name: Include 'deploy_instance.yml' for instance {{ docker_deploy_name }}
  ansible.builtin.include_tasks: deploy_instance.yml
  when: docker_deploy_state == 'present'

- name: Include 'delete_instance.yml' for instance {{ docker_deploy_name }}
  ansible.builtin.include_tasks: delete_instance.yml
  when: docker_deploy_state == 'absent'

- name: Include 'deactivate_instance.yml' for instance {{ docker_deploy_name }}
  ansible.builtin.fail:
    msg: "Not yet implemented"
  when: docker_deploy_state == 'deactivated'

...
